-- MySQL Script generated by MySQL Workbench
-- Thu Dec  4 19:35:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema csci402_project_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csci402_project_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csci402_project_schema` DEFAULT CHARACTER SET utf8mb3 ;
USE `csci402_project_schema` ;

-- -----------------------------------------------------
-- Table `csci402_project_schema`.`project_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`project_plan` (
  `project_id` CHAR(10) NOT NULL COMMENT 'Primary Identifier',
  `project_name` VARCHAR(100) NOT NULL COMMENT 'Name of the project require',
  `project_type` VARCHAR(500) NOT NULL COMMENT 'Description of the project',
  `funds_recovered` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Funds recovered from previous projects that could be used for later projects\\n\\n',
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`village`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`village` (
  `village_id` CHAR(10) NOT NULL COMMENT 'Primary identifier\\n',
  `village_name` VARCHAR(100) NOT NULL COMMENT 'Name of the village is required for location',
  `longitude` FLOAT NULL DEFAULT NULL COMMENT 'optional info of the village',
  `latitude` FLOAT NULL DEFAULT NULL COMMENT 'optional info of the village',
  `village_size` INT NULL DEFAULT NULL COMMENT 'Number of people in the village',
  PRIMARY KEY (`village_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`request` (
  `request_id` CHAR(10) NOT NULL COMMENT 'Primary identifier ',
  `project_request` VARCHAR(500) NOT NULL COMMENT 'Required description of the village need and request in order to best accomodate a project\\n',
  `village_id` CHAR(10) NOT NULL COMMENT 'FK link to VILLAGE',
  PRIMARY KEY (`request_id`, `village_id`),
  INDEX `fk_REQUEST_VILLAGE1` (`village_id` ASC) VISIBLE,
  CONSTRAINT `fk_REQUEST_VILLAGE1`
    FOREIGN KEY (`village_id`)
    REFERENCES `csci402_project_schema`.`village` (`village_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`assigment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`assigment` (
  `assigment_id` CHAR(10) NOT NULL COMMENT 'Primary identifier',
  `request_id` CHAR(10) NOT NULL COMMENT 'FK link to REQUEST\\n',
  `start_date` DATE NOT NULL COMMENT 'Must know when the assigment starts\\n',
  `end_date` DATE NOT NULL COMMENT 'Optional because the assigment can be null if still working on assigment',
  `location` VARCHAR(100) NOT NULL COMMENT 'Where the assigment is at',
  `project_id` CHAR(10) NOT NULL COMMENT 'FK links to PROJECT PLAN\\n',
  PRIMARY KEY (`assigment_id`, `project_id`, `request_id`),
  INDEX `fk_ASSIGMENT_PROJECT PLAN1` (`project_id` ASC) VISIBLE,
  INDEX `fk_ASSIGMENT_REQUEST1` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_ASSIGMENT_PROJECT PLAN1`
    FOREIGN KEY (`project_id`)
    REFERENCES `csci402_project_schema`.`project_plan` (`project_id`),
  CONSTRAINT `fk_ASSIGMENT_REQUEST1`
    FOREIGN KEY (`request_id`)
    REFERENCES `csci402_project_schema`.`request` (`request_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`donor` (
  `donor_id` CHAR(10) NOT NULL COMMENT 'Primary Identifier',
  `donor_name` VARCHAR(100) NOT NULL COMMENT 'Donor must have a name, if anonymus state ANONYM',
  `donor_email` VARCHAR(100) NOT NULL COMMENT 'Donor must have an email for communication',
  PRIMARY KEY (`donor_id`),
  UNIQUE INDEX `donor_email_UNIQUE` (`donor_email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`donation` (
  `donation_id` CHAR(10) NOT NULL COMMENT 'Primary Identifier',
  `donor_id` CHAR(10) NOT NULL COMMENT 'FK link to DONOR',
  `project_id` CHAR(10) NOT NULL COMMENT 'FK link to PROJECT PLAN',
  `amount_donated` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT 'Amount donated from the donor',
  `donation_date` DATE NOT NULL COMMENT 'When the donation was given',
  PRIMARY KEY (`donation_id`, `donor_id`, `project_id`),
  INDEX `fk_DONATION_PROJECT PLAN1` (`project_id` ASC) VISIBLE,
  INDEX `fk_DONATION_DONOR1` (`donor_id` ASC) VISIBLE,
  CONSTRAINT `fk_DONATION_DONOR1`
    FOREIGN KEY (`donor_id`)
    REFERENCES `csci402_project_schema`.`donor` (`donor_id`),
  CONSTRAINT `fk_DONATION_PROJECT PLAN1`
    FOREIGN KEY (`project_id`)
    REFERENCES `csci402_project_schema`.`project_plan` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`expertise` (
  `expertise_id` CHAR(10) NOT NULL COMMENT 'Primary identifier',
  `name` VARCHAR(100) NOT NULL COMMENT 'Field name (eg. Math)',
  `description` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Description of the field is optional\\n',
  `team_size` INT NOT NULL COMMENT 'How many people is on the team',
  `project_id` CHAR(10) NOT NULL COMMENT 'FK link to PROJECT PLAN',
  PRIMARY KEY (`expertise_id`, `project_id`),
  INDEX `fk_EXPERTISE_PROJECT PLAN1` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_EXPERTISE_PROJECT PLAN1`
    FOREIGN KEY (`project_id`)
    REFERENCES `csci402_project_schema`.`project_plan` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`volunteer` (
  `volunteer_id` CHAR(10) NOT NULL COMMENT 'Primary identifier',
  `volunteer_name` VARCHAR(100) NOT NULL COMMENT 'Name of the volunteer is required',
  `volunteer_email` VARCHAR(100) NOT NULL COMMENT 'Email of the volunteer is required for communication',
  `volunteer_phone` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Phone number can be optional since we already have the email',
  `location` VARCHAR(100) NOT NULL COMMENT 'Where the volunteer is from is optional',
  `volunteer_type` VARCHAR(15) NOT NULL COMMENT 'Specifying either a \"Expert\" or \"Non-Expert\"',
  `availability` DATE NOT NULL,
  `expertise_id` CHAR(10) NOT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`volunteer_id`, `expertise_id`),
  UNIQUE INDEX `volunteer_email_UNIQUE` (`volunteer_email` ASC) VISIBLE,
  INDEX `fk_Volunteer_Expertise1` (`expertise_id` ASC) VISIBLE,
  CONSTRAINT `fk_Volunteer_Expertise1`
    FOREIGN KEY (`expertise_id`)
    REFERENCES `csci402_project_schema`.`expertise` (`expertise_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`expert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`expert` (
  `volunteer_id` CHAR(10) NOT NULL,
  `expertise_area` VARCHAR(100) NOT NULL,
  `certifications` TINYINT NOT NULL,
  `years_of_experience` INT NOT NULL,
  PRIMARY KEY (`volunteer_id`),
  CONSTRAINT `fk_Expert_Volunteer1`
    FOREIGN KEY (`volunteer_id`)
    REFERENCES `csci402_project_schema`.`volunteer` (`volunteer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `csci402_project_schema`.`non_expert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csci402_project_schema`.`non_expert` (
  `volunteer_id` CHAR(10) NOT NULL,
  `skills` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`volunteer_id`),
  CONSTRAINT `fk_Non_Expert_Volunteer1`
    FOREIGN KEY (`volunteer_id`)
    REFERENCES `csci402_project_schema`.`volunteer` (`volunteer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
